# Generated by Django 3.2.6 on 2021-08-24 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localization', models.CharField(max_length=32, verbose_name='Localization')),
                ('localization_en', models.CharField(max_length=32, null=True, verbose_name='Localization')),
                ('localization_pt', models.CharField(max_length=32, null=True, verbose_name='Localization')),
                ('secret', models.CharField(max_length=32, verbose_name='Secret')),
                ('owner', models.CharField(max_length=32, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Experimental apparatus',
                'verbose_name_plural': 'Experimental apparatuses',
                'ordering': ['localization'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('name_en', models.CharField(max_length=64, null=True, verbose_name='Name')),
                ('name_pt', models.CharField(max_length=64, null=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_pt', models.TextField(null=True, verbose_name='Description')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('scientific_area', models.CharField(max_length=64, verbose_name='Scientific area')),
                ('scientific_area_en', models.CharField(max_length=64, null=True, verbose_name='Scientific area')),
                ('scientific_area_pt', models.CharField(max_length=64, null=True, verbose_name='Scientific area')),
                ('lab_type', models.CharField(max_length=32, verbose_name='Lab type')),
                ('lab_type_en', models.CharField(max_length=32, null=True, verbose_name='Lab type')),
                ('lab_type_pt', models.CharField(max_length=32, null=True, verbose_name='Lab type')),
            ],
            options={
                'verbose_name': 'Experiment',
                'verbose_name_plural': 'Experiments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Time')),
                ('result_type', models.CharField(max_length=64, verbose_name='Result type')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Time')),
                ('status', models.CharField(choices=[('1', 'Online'), ('0', 'Offline'), ('R', 'Running')], max_length=1, verbose_name='Status')),
                ('apparatus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='free.apparatus')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64, null=True)),
                ('name_pt', models.CharField(max_length=64, null=True)),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('apparatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='free.apparatus')),
            ],
            options={
                'verbose_name': 'Experimental protocol',
                'verbose_name_plural': 'Experimental protocols',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('status', models.CharField(max_length=32, verbose_name='Status')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='free.protocol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protocol execution',
                'verbose_name_plural': 'Protocol executions',
            },
        ),
        migrations.AddField(
            model_name='apparatus',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='free.experiment'),
        ),
    ]
