# Generated by Django 3.2.6 on 2021-09-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_squashed_0007_auto_20210901_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparatus',
            name='location',
            field=models.CharField(max_length=64, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='apparatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='free.apparatus'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='free.experiment'),
        ),
        migrations.AlterField(
            model_name='result',
            name='execution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='free.execution'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_type',
            field=models.CharField(choices=[('f', 'Final'), ('p', 'Partial')], max_length=1, verbose_name='Result type'),
        ),
    ]
