# Generated by Django 3.2.6 on 2021-09-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0002_auto_20210921_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('C', 'Configured'), ('R', 'Running'), ('E', 'Error'), ('F', 'Finished')], max_length=1, verbose_name='Status'),
        ),
    ]
