# Generated by Django 3.2.6 on 2021-11-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0007_alter_result_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-time'], 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AddField(
            model_name='experiment',
            name='slug',
            field=models.SlugField(default='fillme', max_length=64, verbose_name='Slug name'),
            preserve_default=False,
        ),
    ]
