# Generated by Django 3.2.6 on 2021-11-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0008_auto_20211102_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparatus',
            name='video_config',
            field=models.JSONField(blank=True, null=True, verbose_name='Video configuration'),
        ),
        migrations.AddField(
            model_name='execution',
            name='queue_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('C', 'Configured'), ('Q', 'In queue'), ('R', 'Running'), ('E', 'Error'), ('F', 'Finished'), ('A', 'Aborted'), ('T', 'Timeout')], max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_type',
            field=models.CharField(choices=[('f', 'Final'), ('p', 'Partial')], max_length=1, verbose_name='Result type'),
        ),
    ]
