# Generated by Django 3.2.9 on 2021-11-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0010_auto_20211105_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparatus',
            name='location_es',
            field=models.CharField(max_length=64, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='lab_type_es',
            field=models.CharField(max_length=32, null=True, verbose_name='Lab type'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='name_es',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='scientific_area_es',
            field=models.CharField(max_length=64, null=True, verbose_name='Scientific area'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='name_es',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_type',
            field=models.CharField(choices=[('p', 'Partial'), ('f', 'Final')], max_length=1, verbose_name='Result type'),
        ),
    ]
