# Generated by Django 3.2.9 on 2021-11-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0011_auto_20211116_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-id'], 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AddField(
            model_name='apparatus',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuration'),
        ),
    ]
