# Generated by Django 3.2.9 on 2021-12-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0013_auto_20211229_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result_type',
            field=models.CharField(choices=[('p', 'Partial'), ('f', 'Final')], max_length=1, verbose_name='Result type'),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_last',
            field=models.BooleanField(default=True, verbose_name='Is last?'),
        ),
    ]
