# Generated by Django 3.2.9 on 2022-02-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0018_auto_20220217_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocol',
            old_name='experiment',
            new_name='apparatus_type',
        ),
        migrations.RemoveField(
            model_name='apparatus',
            name='experiment',
        ),
        migrations.AddField(
            model_name='apparatus',
            name='apparatus_type',
            field=models.ForeignKey(default=1, help_text='After setting/changing the apparatus_type, press "Save and continue editing" to see the list of protocols.', on_delete=django.db.models.deletion.PROTECT, to='free.apparatustype'),
            preserve_default=False,
        ),
    ]
