# Generated by Django 3.2.9 on 2022-04-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0021_auto_20220421_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
