# Generated by Django 4.0.5 on 2022-06-07 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0023_alter_result_result_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
