# Generated by Django 4.1.1 on 2022-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0025_alter_result_result_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparatus',
            name='image',
            field=models.ImageField(default='apparatus/missing_image.jpg', upload_to='apparatus/'),
        ),
    ]
